### ISSUE TITLE
Tooling and app should compile and run when no components are found

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Tooling-Windows-Submodule#32]
## Background
The tooling was created in Toolkit Labs, and was created using CanvasLayout as our testing ground. The tooling has only ever been used with at _least_ one component present.

## Problem
The tooling fails in some places when no components are found. This manifests in various forms.

## Solution
This issue documents and tracks the various problems we've found when no components are present. See comments below.

**Comment by Arlodotexe** [comment]
## Summary
We had to revert 51a666f0a16157f0a3131ab6730cdc1309dd7d4a in #27. 

### Why this was added
This a general tooling fix from #27 that we found while doing https://github.com/CommunityToolkit/Windows/pull/1: `A compiler error that occurs when the only component in the solution doesn't support all MultiTargets.` Would also happen if no component in the solution supported a MultiTarget you had loaded (e.g. if you decided to exclude Android altogether but still generated the Android head).

We found this by removing WASM on the converters experiment, which caused WASM to compile without any components, while the UWP and WinAppSDK heads had the Converters. This fix was a quick thing to move us towards allow compiling the app without components (and to get https://github.com/CommunityToolkit/Windows/pull/1 out the door).

### Why this was removed
This caused the [CI to fail here](https://github.com/CommunityToolkit/Windows/actions/runs/4471769409/jobs/7857538533#step:16:21).

```
Error Message:
   Test method CommunityToolkit.Tooling.SampleGen.Tests.ToolkitSampleMetadataTests.PaneOption_GeneratesTitleProperty threw exception: 
System.InvalidOperationException: Sequence contains no matching element
  Stack Trace:
      at System.Linq.ThrowHelper.ThrowNoMatchException()
   at CommunityToolkit.Tooling.SampleGen.Tests.ToolkitSampleMetadataTests.VerifyGenerateSources(String assemblyName, String source, IIncrementalGenerator[] generators, Boolean ignoreDiagnostics, ValueTuple`2[] results) in /_/CommunityToolkit.Tooling.SampleGen.Tests/ToolkitSampleMetadataTests.cs:line 533
   at CommunityToolkit.Tooling.SampleGen.Tests.ToolkitSampleMetadataTests.PaneOption_GeneratesTitleProperty() in /_/CommunityToolkit.Tooling.SampleGen.Tests/ToolkitSampleMetadataTests.cs:line 91
```

### Notes:
- The source generator will generate the correct output, but then it runs again and overwrites it with an empty registry. This is what the test picked up and tried to use.
- The (now reverted) commit from #27 was made to allow generating empty registries, and an empty registry is being incorrect generated when running from the test project. The commit has exposed an underlying bug, which now needs to be fixed.
- This is _only_ a problem for the `PaneOption_GeneratesTitleProperty` test, because it's the only test which checks a hardcoded string against the generated output. All other tests simply check the diagnostic.
- We're executing the generator twice. Once for running diagnostics on referenced assemblies, one for running actually generating a registry:
   - ![image](https://user-images.githubusercontent.com/9384894/226700521-7094f66e-537a-40e2-bec1-d987c027d7fe.png)
- We also execute twice inside `Execute` method. The second pass seems to be dedicated to tests, though it's not immediately clear what the intended conditions to reach this code path are. @michael-hawker may have more insight.
   - ![image](https://user-images.githubusercontent.com/9384894/226701465-c8ae25bd-39bf-4df4-aec9-ce9d8df0e470.png)


### What's next?

This is where my investigation ended. Once we fix this underlying bug, we can add this back and enable compiling heads even if they don't reference a project.

Additionally, while there are notes in the code, the code is a bit messy and hard to understand. Since we already need to pull it apart in order to understand and change it, we should rename things to make the intent _explicitly clear_ from how we use it. This source generator is doing too much to fall behind in this area.
